# Generated by Django 4.0.3 on 2022-03-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('email', models.CharField(max_length=60, verbose_name='email')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
            ],
        ),
    ]
